# Generated by Django 4.1.1 on 2022-09-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره موبایل'),
        ),
    ]
