# Generated by Django 4.1.1 on 2022-09-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(blank=True, null=True, upload_to='posts/%Y-%d-%m', verbose_name='محتوا')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='توضیح')),
                ('share_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('views', models.IntegerField(default=1, verbose_name='بازدید')),
                ('like', models.IntegerField(default=0, verbose_name='پسندیده')),
                ('title', models.CharField(max_length=50, verbose_name='موضوع')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مطلب',
                'verbose_name_plural': 'مطالب',
            },
        ),
        migrations.CreateModel(
            name='viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(auto_now_add=True, verbose_name='تاریخ دیده شدن')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='massage.post', verbose_name='محتوا')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='بیننده')),
            ],
            options={
                'verbose_name': 'بیننده',
                'verbose_name_plural': 'بیننده ها',
            },
        ),
    ]
